{{- $fullName := include "deployment.fullname" . -}}

{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Pod
metadata:
    name: "{{ $fullName }}-redis"
spec:
    containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          volumeMounts:
              - name: redis-storage
                mountPath: /data/redis
          ports:
            - containerPort: 6379
    volumes:
        - name: redis-storage
          emptyDir: { }
{{- end }}
