{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment.serviceAccountName" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "en-marche-{{ .Values.environment }}@en-marche-{{ .Values.environment }}.iam.gserviceaccount.com"
{{- end }}
